site_name: TeleFeed Docs
theme:
  name: material
  highlightjs: false
  palette:
      primary: teal
      accent: red
  features:
      - navigation.instant
      - navigation.expand
      - header.autohide

extra_css: [extra.css]
