site_name: TeleFeed Docs
site_dir: "docs/"

theme:
  name: material
  highlightjs: false
  palette:
      primary: teal
      accent: red
  features:
      - navigation.instant
      - navigation.expand
      - toc.integrate
nav:
    - Overview: "index.md"
    - Commands: "commands.md"
    - Faq:
        - Questions: "faq_questions.md"
        - Issues: "faq_issues.md"

extra_css: [extra.css]
