site_name: TeleFeed Docs
site_dir: "docs/"

theme:
  name: material
  highlightjs: false
  palette:
      primary: teal
      accent: red
  features:
      - navigation.tabs
  font:
    text: Roboto

markdown_extensions:
    - abbr
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true

nav:
    - Overview: "index.md"
    - Commands: "commands.md"
    - Faq:
        - Questions: "faq_questions.md"
        - Issues: "faq_issues.md"
    - Known Limitations: "know_limitations.md"

plugins:
  - macros

extra_css: [extra.css]
